name: flutter_chat
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.0 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    socket_io_client: ^2.0.3
    http: ^1.1.0
    provider: ^6.0.5
    freezed_annotation: ^2.4.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    freezed: ^2.4.3
    build_runner: ^2.4.6
    json_annotation: ^4.8.1

flutter:
    uses-material-design: true
